#!/bin/sh

echo "Setting permissions on rfm12piphp script:"
chmod 755 /etc/init.d/rfm12piphp

echo "Configuring system to load rfm12piphp script on boot:"
update-rc.d rfm12piphp defaults

echo "Attempting to (re)start the rfm12piphp script:"
service rfm12piphp restart
echo ""

echo "Installation complete."
echo " - this module's settings are configured directly through the 'Raspberry Pi' section of the emoncms web interface."
echo " - you may wish to run the 'update & check database' tool, accessible via the 'Admin' section of the emoncms web interface."

exit 0
